### ISSUE TITLE
KeyError: 'Gateway_Physical'

### ISSUE THREAD

**Issue by PhilipSchmid** [yantisj/netgrph#4]
Hi there,
I just tried to install netgrph using a Docker-Compose setup. Unfortunately the `first_import.sh` script does not seem to work properly. There seems to be a `KeyError` (see [gateway_physical_error.txt](https://github.com/yantisj/netgrph/files/1238983/gateway_physical_error.txt)). Do you have an idea how to fix this? Thanks!
Regards,
Philip

**Comment by PhilipSchmid** [comment]
In `nglib/net_update.py` the following columns are used:

```bash
 router = net['Router']
 gateway = net['Gateway']
 cidr = net['Subnet']
 desc = net['Description']
 vrf = net['VRF']
 vlan = net['VLAN']
 p2p = net['P2P']
 standby = net['Standby']
 rip = net['Gateway_Physical']
 vpriority = net['Virtual_Priority']
 vgroup = net['Virtual_Group']
 vproto = net['Virtual_Protocol']
 vver = net['Virtual_Version']
```

In `/test/csv/allnets.csv` only the following columns are defined:
```bash
Subnet,VLAN,VRF,Router,Gateway,MGMT Group,Description,P2P,Standby
```

Doesn't they have to correlate with each other?

Regards,
Philip

**Comment by yantisj** [comment]
Philip,

We're in the process of a major network refresh (thanks to this program), so I need to rebuild my test network from the new network, which I will work on. In the meantime, I have fixed the tests with the original network, and set the Physical Gateway to be the regular Gateway for now and ignored HSRP/VRRP in the test network. Grab the latest dev branch and see how that goes now, and I will work on generating a new test network.

**Comment by PhilipSchmid** [comment]
Hi @yantisj,

Awesome, thanks! The script now worked except 1 test:
```bash
py.test-3 is /usr/bin/py.test-3
============================================================================================================================ test session starts =============================================================================================================================
platform linux -- Python 3.5.2, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /opt/netgrph/netgrph, inifile: 
collected 4 items 

ngtest.py .F

================================================================================================================================== FAILURES ==================================================================================================================================
______________________________________________________________________________________________________________________________ test_dev_queries ______________________________________________________________________________________________________________________________

    def test_dev_queries():
        """netgrph query testing"""
    
        print("Testing Query Routines")
    
        for key in qtest.keys():
            print(key)
>           assert(run_query(ngcmd, key, qtest[key])) == True
E           assert run_query('./netgrph.py ', '-vtree ABC-120', '10.1.120.0/23') == True

ngtest.py:122: AssertionError
---------------------------------------------------------------------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------------------------------------------------------------------
Testing Query Routines
-vtree ABC-120
---------------------------------------------------------------------------------------------------------------------------- Captured stderr call ----------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "./netgrph.py", line 349, in <module>
    nglib.query.vlan.get_vtree(args.search, rtype=rtype)
  File "/opt/netgrph/netgrph/nglib/query/vlan.py", line 124, in get_vtree
    nglib.query.exp_ngtree(ngtree, rtype)
  File "/opt/netgrph/netgrph/nglib/query/__init__.py", line 56, in exp_ngtree
    nglib.ngtree.print_ngtree(ngtree, dtree=dict())
  File "/opt/netgrph/netgrph/nglib/ngtree/__init__.py", line 127, in print_ngtree
    print("{:}\u250c\u2500[{:} ]".format(indent, header))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

===================================================================================================================== 2 tests deselected by '-ktest_dev' =====================================================================================================================
============================================================================================================= 1 failed, 1 passed, 2 deselected in 12.92 seconds ==============================================================================================================
```

Regards,
Philip

**Comment by PhilipSchmid** [comment]
Stale. Not interested anymore.
